import type { Metadata } from "next";
import Header from "./components/header";
import Footer from "./components/footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col" data-theme="gunrock">
        <div className="flex-1 flex flex-col">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
